semi: false
singleQuote: true
trailingComma: all
overrides:
  - files: "*.json[c|5]"
    options:
      quoteProps: preserve
      singleQuote: false
  - files: "*.y[a]ml"
    options:
      singleQuote: false
  - files: "*.httpie"
    options:
      printWidth: 200
